### ISSUE TITLE
Dash has Chainlocks and LLMQ InstantSend and now requires 0 conf to be more secure than 6 bitcoin confirmations

### ISSUE THREAD

**Issue by dazbarlby** [lukechilds/howmanyconfs.com#10]
Dash has Chainlocks and LLMQ InstantSend and now requires 0 conf to be as secure as 6 bitcoin confirmations. Please change you website to reflect this, if this is not done then people should consider this site to be spreading FUD.

Thank you

**Comment by lukechilds** [comment]
https://github.com/lukechilds/howmanyconfs.com/issues/9
