### ISSUE TITLE
Dash Chainlocks

### ISSUE THREAD

**Issue by amp127** [lukechilds/howmanyconfs.com#11]
Since you made this dash implemented chainlocks which secures dash through a check point type system. The cost of a attack is now 51% of the hashing power and 60% of the staked masternodes from what i understand. As of today there are 4923 masternodes that have dash staked.  4923MN   ×   $80000MNcost   ×   60% = 236million. All these transactions are locked immediately in the mempool too. Conformations for dash are almost entirely a non-consideration now. Especially if you consider it's nearly impossible to buy 60% of MN's

**Comment by lukechilds** [comment]
https://github.com/lukechilds/howmanyconfs.com/issues/9
