### ISSUE TITLE
The fastest cryptocurrency (Nano) is missing from the website

### ISSUE THREAD

**Issue by qwahzi** [lukechilds/howmanyconfs.com#14]
Hello all,

I couldn't find Nano listed on your website. It uses Open Representative Voting (ORV) instead of Proof of Work (PoW) for consensus, and median confirmation times for irreversibility (i.e. full-conf) are around 0.18 seconds: 

https://repnode.org/network/propagation-confirmation

https://www.nanospeed.live/Stats

Due to block cementing, transactions cannot be reversed even in a 51% attack. Furthermore, since every account has its own blockchain, attackers can't reverse or spend other people's Nano because they won't have the account's private key

Regards,
Qwahzi

**Comment by lukechilds** [comment]
See https://github.com/lukechilds/howmanyconfs.com/issues/3
