### ISSUE TITLE
KMD stats

### ISSUE THREAD

**Issue by TheComputerGenie** [lukechilds/howmanyconfs.com#17]
Does not account for dPoW

**Comment by lukechilds** [comment]
Oops, KMD should be blacklisted. HUSH and ARRR too.

Looks like I was previously using a third party API that already blacklisted them. When that went down I implemented everything internally but forgot to copy over the blacklisted coins.

I should have time to fix this tomorrow.

**Comment by lukechilds** [comment]
Resolved in https://github.com/lukechilds/howmanyconfs.com/commit/a425617c966665647c9fc52723d141b12cb44068
