### ISSUE TITLE
adding DCR Decred

### ISSUE THREAD

**Issue by raedah** [lukechilds/howmanyconfs.com#4]
Decred is a hybrid PoW/PoS chain.

More data is here https://explorer.dcrdata.org/

https://explorer.dcrdata.org/charts?chart=hashrate

**Comment by lukechilds** [comment]
See https://github.com/lukechilds/howmanyconfs.com/issues/3

**Comment by raedah** [comment]
Decred is PoW, with an additional PoS layer. Quite surprised that would exclude it.

**Comment by lukechilds** [comment]
PoW with PoS is not comparible with just PoW with the metrics I'm using.
