### ISSUE TITLE
Price x block / double spend

### ISSUE THREAD

**Issue by HostFat** [lukechilds/howmanyconfs.com#5]
I can be interesting if you add a way to easy understand the cost of a double spend for every cryptocurrecy.

>Bitcoin's total $ cost for 6 confirmations is ($100 * 3,600 seconds) $360,000

This generally means that if I've to receive a transfer of $360,000 I should wait 6 confirmation on Bitcoin. 
The miner has an incentive to not try to double spend his tx if I'm waiting 6 confirmation and the value in $  transfered is less then that value ($360,000)

If the value is way higher (like 1 billion), maybe even 6 confirmations aren't anymore enough.

The same, for every other cryptocurreny on your list.

Something like that the user can enter somewhere how much he wants to receive (in usd), and the website will advise which is the right amount of confirmations that he should wait on that chain. (because the cost to double spend will be higher then the value of the tx)

Currently your website has this fixed amount set on the cost to double spend a tx with 6 confirmation on Bitcoin.

The user should be able to change it.

**Comment by lukechilds** [comment]
>I can be interesting if you add a way to easy understand the cost of a double spend for every cryptocurrecy.
>
>>Bitcoin's total $ cost for 6 confirmations is ($100 * 3,600 seconds) $360,000
>
>This generally means that if I've to receive a transfer of $360,000 I should wait 6 confirmation on Bitcoin.
>The miner has an incentive to not try to double spend his tx if I'm waiting 6 confirmation and the value in $ transfered is less then that value ($360,000)

That's not what that value means, I explain that in the readme:

>#### $/s doesn't mean what it sounds like it means.
>The $/s values should not be taken as literal costs.
>
>For example:
>
>Bitcoin's total $ cost for 6 confirmations is ($100 * 3,600 seconds) $360,000
This is does not mean you could do a 51% attack on Bitcoin and roll back 6 blocks for a cost of $360,000. An attack like that would be much more expensive.

- https://github.com/lukechilds/howmanyconfs.com#s-doesnt-mean-what-it-sounds-like-it-means
