### ISSUE TITLE
Sorting by Proof of Work, doesn't work...

### ISSUE THREAD

**Issue by SalvorinFex** [lukechilds/howmanyconfs.com#8]
Hey there,  It seems that sorting by `Proof of Work`  doesn't completely sort by that.
I thin the other ones are fine.

**Comment by lukechilds** [comment]
Good spot, thanks.

It's sorting by raw no of hashes, which obviously doesn't make sense between algs.

I will change to order by the same as the "Difference" column, so it'll order by "thermodynamic hash power".

**Comment by lukechilds** [comment]
Resolved in https://github.com/lukechilds/howmanyconfs.com/commit/0d7c43105a119c9b5e2ead9ce9cd2c902246aad3.

Thanks @SalvorinFex!
